/*
 direction.js (c) 2015 Ogewan, MIT*/
 direction=function(t,k,w,b){function I(){try{jQuery.A.direction=function(a,e,d){return this.w(function(){direction(a,$(this),e,d)})}}catch(a){console.log(a)}}function x(a,e){y=!0;window.setTimeout(z,A,B);l.g("start");0>e&&(e=0);e>=c.length&&(e=c.length-1);if(!(0>e)){c[e].c||m.clearRect(0,0,d[1].width,d[1].height);a.b=e;a.src=g.dir+c[e].h;n=e;var b=0,h;for(h=e-1;h>e-g.j-1&&0<=h;h--)c[h].c||(p[b].b=h,p[b].src=g.dir+c[h].h,b++);b=0;for(h=e+1;h<g.l+e+1&&h<c.length;h++)c[h].c||(q[b].b=h,q[b].src=g.dir+
    c[h].h,b++)}}function G(){c[this.b].c=!0}function H(a,b){function d(a,b,e){window.scrollBy(Math.floor(a.x)/b,Math.floor(a.y)/b);e+1<5*b&&window.setTimeout(d,5,a,b,e+1)}if(null===a||void 0===a)a={x:0,y:0};else if(isNaN(a)){if(null===a.y||void 0===a.y)a.y=0;if(null===a.x||void 0===a.x)a.x=0}else a={x:0,y:a};if(null===b||void 0===b||0>=b)b=400;0>a.y&&(a.y=window.innerHeight||u.clientHeight||E.clientHeight);0>a.x&&(a.x=window.innerWidth||u.clientWidth||E.clientWidth);var e={x:void 0!==window.pageXOffset?
    a.x-window.pageXOffset:a.x-u.scrollLeft,y:void 0!==window.pageYOffset?a.y-window.pageYOffset:a.y-u.scrollTop};if(e=={x:0,y:0})return e;window.setTimeout(d,5,e,Math.floor(b/5),0);return e}function z(a){d[0].style.paddingLeft=(d[1].width-300)/2+"px";var b=Math.floor((Date.now()-a.start)/1E3*a.lines)/a.lines,c=a.color.substr(1);a.a.save();a.a.clearRect(0,0,300,d[1].height);a.a.translate(150,d[1].height/2);a.a.rotate(2*Math.PI*b);3==c.length&&(c=c[0]+C[0]+c[1]+c[1]+c[2]+c[2]);b=r(c.substr(0,2),16).toString();
    var f=r(c.substr(2,2),16).toString();c=r(c.substr(4,2),16).toString();for(var g=0;g<a.lines;g++)a.a.beginPath(),a.a.rotate(2*Math.PI/a.lines),a.a.moveTo(a.f/10,0),a.a.lineTo(a.f/4,0),a.a.lineWidth=a.f/30,a.a.strokeStyle="rgba("+b+","+f+","+c+","+g/a.lines+")",a.a.stroke();a.a.restore();y?window.setTimeout(z,a.m,B):a.a.clearRect(0,0,300,d[1].height)}if(void 0===t)return-1;w=w||0;b=b||{};var v=document,E=v.body,u=v.documentElement,r=parseInt;if(void 0===k||null==k)k=E;var c=t.slice().map(function(a){return{h:a}}),
    y=!0,n=-1;t=b.lines||16;var A=b.m||1E3/30,J=b.v||250,K=b.F||"#FFF",L=b.color||"#373737",g={dir:b.dir||"",j:b.C||5,l:b.B||5,back:b.back||"#FFF",i:b.size||{u:void 0,s:void 0},o:0},q=[],p=[],f=new Image,F=!0,d=[v.createElement("canvas"),v.createElement("canvas")],m=d[1].getContext("2d"),l={g:function(a){for(var b=0;b<l[a].length;b++)l[a][b]()},start:[],H:[],G:[]},B={a:d[0].getContext("2d"),color:L,start:Date.now(),lines:t,f:J,m:A};window.D&&I();this.count=function(){return c.length};this.current=function(){return n};
    this.go=function(a){a=null===a||void 0===a?0:r(a,10);a=isNaN(a)?0:a;x(f,Math.floor(Math.max(0,Math.min(c.length-1,a))));return a};this.next=function(){var a=n+1;a<c.length&&x(f,a);return a};this.data=function(a){a=null===a||void 0===a?n:r(a,10);return isNaN(a)?c[n]:c[Math.floor(Math.max(0,Math.min(c.length-1,a)))]};this.scroll=function(a){null!==a&&void 0!==a&&(F=a);return F};this.scrollTo=function(a,b){return H(a,b)};d[0].height=480;d[0].style.background=K;d[0].style.paddingLeft="170px";d[0].style.zIndex=
    0;d[0].style.position="absolute";k.appendChild(d[1]);window.setTimeout(z,A,B);f=new Image;f.b=-1;f.addEventListener("load",function(){c[f.b].c?m.clearRect(0,0,f.width,f.height):c[f.b].c=!0;l.g("slidn");if(g.i)m.drawImage(f,0,0,g.i.u,g.i.s);else{switch(g.o){case 1:var a=f.width/d[1].width;a=[d[1].width,f.height*a];break;case 2:a=f.height/d[1].height;a=[f.width*a,d[1].height];break;default:a=g.o?[d[1].width,d[1].height]:[f.width,f.height]}d[1].width=a[0];d[1].height=d[0].height=a[1];m.drawImage.apply(m,
    [f,0,0].concat(a))}y=0;F&&H();l.g("slidd")},!1);for(b=0;b<c.length;b++)c[b].d=b?b==c.length-1?1:0:-1,c[b].c=!1;for(b=0;b<g.j;b++)p.push(new Image),p[b].b=-1,p[b].addEventListener("load",G,!1);for(b=0;b<g.l;b++)q.push(new Image),q[b].b=-1,q[b].addEventListener("load",G,!1);x(f,g.I||w);d[1].height=480;d[1].width=640;d[1].background=g.back;d[1].style.zIndex=1;d[1].style.position="relative";k.appendChild(d[1])};