/*
 direction.js (c) 2015 Seun Ogedengbe, MIT*/
 direction=function(r,g,t,b){function E(){try{jQuery.l.direction=function(a,F,b){return this.j(function(){direction(a,$(this),F,b)})}}catch(a){console.log("failed to attach to jQuery")}}function u(a,b){v=!0;window.setTimeout(w,x,y);l.g("start");0>b&&(b=0);b>=c.length&&(b=c.length-1);c[b].loaded||z.clearRect(0,0,d[1].width,d[1].height);a.a=b;a.src=f.dir+c[b];n=b;var h=0,e;for(e=b-1;e>b-f.f-1&&0<=e;e--)c[e].loaded||(p[h].a=e,p[h].src=f.dir+c[e],h++);h=0;for(e=b+1;e<f.c+b+1&&e<c.length;e++)c[e].loaded||
 (q[h].a=e,q[h].src=f.dir+c[e],h++)}function B(){c[this.a].loaded=!0}function D(a,b){function d(a,b,c){window.scrollBy(Math.floor(a.x)/b,Math.floor(a.y)/b);c+1<5*b&&window.setTimeout(d,5,a,b,c+1)}if(null===a||void 0===a)a={x:0,y:0};else if(isNaN(a)){if(null===a.y||void 0===a.y)a.y=0;if(null===a.x||void 0===a.x)a.x=0}else a={x:0,y:a};if(null===b||void 0===b||0>=b)b=400;0>a.y&&(a.y=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight);0>a.x&&(a.x=window.innerWidth||document.documentElement.clientWidth||
 document.body.clientWidth);var c={x:void 0!==window.pageXOffset?a.x-window.pageXOffset:a.x-document.documentElement.scrollLeft,y:void 0!==window.pageYOffset?a.y-window.pageYOffset:a.y-document.documentElement.scrollTop};if(c=={x:0,y:0})return c;window.setTimeout(d,5,c,Math.floor(b/5),0);return c}function w(a){d[0].style.paddingLeft=(d[1].width-300)/2+"px";var b=Math.floor((Date.now()-a.start)/1E3*a.lines)/a.lines,c=a.color.substr(1);a.context.save();a.context.clearRect(0,0,300,d[1].height);a.context.translate(150,
 d[1].height/2);a.context.rotate(2*Math.PI*b);3==c.length&&(c=c[0]+C[0]+c[1]+c[1]+c[2]+c[2]);b=parseInt(c.substr(0,2),16).toString();var e=parseInt(c.substr(2,2),16).toString();c=parseInt(c.substr(4,2),16).toString();for(var f=0;f<a.lines;f++)a.context.beginPath(),a.context.rotate(2*Math.PI/a.lines),a.context.moveTo(a.b/10,0),a.context.lineTo(a.b/4,0),a.context.lineWidth=a.b/30,a.context.strokeStyle="rgba("+b+","+e+","+c+","+f/a.lines+")",a.context.stroke();a.context.restore();v?window.setTimeout(w,
 a.h,y):a.context.clearRect(0,0,300,d[1].height)}if(void 0===r)return-1;t=t||0;b=b||{};if(void 0===g||null==g)g=document.body;var c=r.slice(),v=!0,n=-1;r=b.lines||16;var x=b.h||1E3/30,G=b.b||250,H=b.o||"#FFF",I=b.color||"#373737",f={dir:b.dir||"assets/",f:b.f||5,c:b.c||5,back:b.back||"#FFF"},q=[],p=[],k=new Image,A=!0,d=[document.createElement("canvas"),document.createElement("canvas")],z=d[1].getContext("2d"),l={g:function(a){for(var b=0;b<l[a].length;b++)l[a][b]()},start:[],u:[],s:[]},y={context:d[0].getContext("2d"),
 color:I,start:Date.now(),lines:r,b:G,h:x};window.m&&E();this.count=function(){return c.length};this.current=function(){return n};this.go=function(a){a=null===a||void 0===a?0:parseInt(a,10);a=isNaN(a)?0:a;u(k,Math.floor(Math.max(0,Math.min(c.length-1,a))));return a};this.next=function(){var a=n+1;a<c.length&&u(k,a);return a};this.data=function(a){a=null===a||void 0===a?n:parseInt(a,10);return isNaN(a)?c[n]:c[Math.floor(Math.max(0,Math.min(c.length-1,a)))]};this.scroll=function(a){null!==a&&void 0!==
 a&&(A=a);return A};this.scrollTo=function(a,b){return D(a,b)};d[0].height=480;d[0].style.background=H;d[0].style.paddingLeft="170px";d[0].style.zIndex=0;d[0].style.position="absolute";g?g.appendChild(d[0]):document.body.appendChild(d[0]);window.setTimeout(w,x,y);k=new Image;k.a=-1;k.addEventListener("load",function(){c[this.a].loaded?z.clearRect(0,0,this.width,this.height):c[this.a].loaded=!0;l.g("slidn");d[1].width=this.width;d[1].height=d[0].height=this.height;z.drawImage(this,0,0);v=0;A&&D();l.g("slidd")},
 !1);for(b=0;b<c.length;b++)c[b].i=b?b==c.length-1?1:0:-1,c[b].loaded=!1;for(b=0;b<f.f;b++)p.push(new Image),p[b].a=-1,p[b].addEventListener("load",B,!1);for(b=0;b<f.c;b++)q.push(new Image),q[b].a=-1,q[b].addEventListener("load",B,!1);u(k,f.v||t);d[1].height=480;d[1].width=640;d[1].background=f.back;d[1].style.zIndex=1;d[1].style.position="relative";g?g.appendChild(d[1]):document.body.appendChild(d[1])};