/*
 direction.js (c) 2015 Ogewan, MIT*/
 direction=function(v,g){function F(){try{jQuery.C.direction=function(a,b,c){return this.B(function(){direction(a,$(this),b,c)})}}catch(a){console.log(a)}}function w(a,b){x=!0;y(z);m.i("start");0>b&&(b=0);b>=f.length&&(b=f.length-1);if(!(0>b)){f[b].c||t.clearRect(0,0,c[1].width,c[1].height);a.b=b;a.src=k.dir+f[b].j;n=b;var d=0,l;for(l=b-1;l>b-k.m-1&&0<=l;l--)f[l].c||(p[d].b=l,p[d].src=k.dir+f[l].j,d++);d=0;for(l=b+1;l<k.o+b+1&&l<f.length;l++)f[l].c||(q[d].b=l,q[d].src=k.dir+f[l].j,d++)}}function D(){f[this.b].c=
    !0}function E(a,b){function d(a,b,c){window.scrollBy(Math.floor(a.x)/b,Math.floor(a.y)/b);c+1<5*b&&window.setTimeout(d,5,a,b,c+1)}if(null===a||void 0===a)a={x:0,y:0};else if(isNaN(a)){if(null===a.y||void 0===a.y)a.y=0;if(null===a.x||void 0===a.x)a.x=0}else a={x:0,y:a};if(null===b||void 0===b||0>=b)b=400;0>a.y&&(a.y=window.innerHeight||u.clientHeight||A.clientHeight);0>a.x&&(a.x=window.innerWidth||u.clientWidth||A.clientWidth);var c={x:void 0!==window.pageXOffset?a.x-window.pageXOffset:a.x-u.scrollLeft,
    y:void 0!==window.pageYOffset?a.y-window.pageYOffset:a.y-u.scrollTop};if(c=={x:0,y:0})return c;window.setTimeout(d,5,c,Math.floor(b/5),0);return c}function z(){if(d){c[0].style.paddingLeft=(c[1].width-300)/2+"px";var a=Math.floor((Date.now()-d.v)/1E3*d.f)/d.f,b=d.u.substr(1);d.a.save();d.a.clearRect(0,0,300,c[1].height);d.a.translate(150,c[1].height/2);d.a.rotate(2*Math.PI*a);3==b.length&&(b=b[0]+C[0]+b[1]+b[1]+b[2]+b[2]);a=r(b.substr(0,2),16).toString();var f=r(b.substr(2,2),16).toString();b=r(b.substr(4,
    2),16).toString();for(var e=0;e<d.f;e++)d.a.beginPath(),d.a.rotate(2*Math.PI/d.f),d.a.moveTo(d.h/10,0),d.a.lineTo(d.h/4,0),d.a.lineWidth=d.h/30,d.a.strokeStyle="rgba("+a+","+f+","+b+","+e/d.f+")",d.a.stroke();d.a.restore();x?y(z):d.a.clearRect(0,0,300,c[1].height)}}var e=document,A=e.body,u=e.documentElement,r=parseInt,y=window.requestAnimationFrame;v=v||[];g=g||{};owrite=g.J||0;anchor=g.anchor||A;var f=v.slice().map(function(a){return{j:a}}),x=!0,n=-1,c=[g.A?null:e.createElement("canvas"),e.createElement("canvas")],
    d=c[0]?{a:c[0].getContext("2d"),u:g.color||"#373737",v:Date.now(),f:g.lines||16,K:g.rate||1E3/30,h:g.w||250,g:g.I||"#FFF"}:null,k={dir:g.dir||"",m:g.G||5,o:g.F||5,g:g.back||"#FFF",l:g.size||0,s:0},q=[],p=[],h=new Image,B=!0,t=c[1].getContext("2d"),m={i:function(a){for(var b=0;b<m[a].length;b++)m[a][b]()},start:[],M:[],L:[]};window.H&&F();this.count=function(){return f.length};this.current=function(){return n};this.go=function(a){a=null===a||void 0===a?0:r(a,10);a=isNaN(a)?0:a;w(h,Math.floor(Math.max(0,
    Math.min(f.length-1,a))));return a};this.next=function(){var a=n+1;a<f.length&&w(h,a);return a};this.data=function(a){a=null===a||void 0===a?n:r(a,10);return isNaN(a)?f[n]:f[Math.floor(Math.max(0,Math.min(f.length-1,a)))]};this.scroll=function(a){null!==a&&void 0!==a&&(B=a);return B};this.scrollTo=function(a,b){return E(a,b)};d&&(c[0].height=480,c[0].style.background=d.g,c[0].style.paddingLeft="170px",c[0].style.zIndex=0,c[0].style.position="absolute");d&&anchor.appendChild(c[0]);y(z);h=new Image;
    h.b=-1;h.addEventListener("load",function(){f[h.b].c?t.clearRect(0,0,c[1].width,c[1].height):f[h.b].c=!0;m.i("slidn");if(k.l)var a=[k.l.O,k.l.D];else switch(k.s){case 1:a=c[1].width/h.width;a=[c[1].width,h.height*a];break;case 2:a=c[1].height/h.height;a=[h.width*a,c[1].height];break;default:a=k.s?[c[1].width,c[1].height]:[h.width,h.height]}c[1].width=a[0];c[1].height=a[1];d&&(c[0].height=a[1]);t.drawImage.apply(t,[h,0,0].concat(a));x=0;B&&E();m.i("slidd")},!1);for(e=0;e<f.length;e++)f[e].d=e?e==f.length-
    1?1:0:-1,f[e].c=!1;for(e=0;e<k.m;e++)p.push(new Image),p[e].b=-1,p[e].addEventListener("load",D,!1);for(e=0;e<k.o;e++)q.push(new Image),q[e].b=-1,q[e].addEventListener("load",D,!1);w(h,k.N||owrite);c[1].height=480;c[1].width=640;c[1].background=k.g;c[1].style.zIndex=1;c[1].style.position="relative";anchor.appendChild(c[1])};