/*
 infinite(direction).js (c) 2015 Seun Ogedengbe, MIT*/
infinite=function(e,n,x,f,F,G){function t(d,b){y=!0;window.setTimeout(B,p.h,D);0>b&&(b=0);b>=k&&(b=k-1);h[b].loaded||l.clearRect(0,0,c[1].width,c[1].height);for(var g=0;3>g;g++)d[g].a=b-1+g,b-1+g<k&&0<=b-1+g?d[g].src=q.dir+h[b-1+g].url[0]:(d[g].a=-1,d[g].src="");m=b;for(var g=0,a=b-1;a>b-q.m-1&&0<=a;a--)h[a].loaded||(u[g].a=a,u[g].src=q.dir+h[a].url,g++);g=0;for(a=b+1;a<q.l+b+1&&a<k;a++)h[a].loaded||(v[g].a=a,v[g].src=q.dir+h[a].url,g++)}function H(){h[this.a].loaded=!0}function w(d,a,g){y=0;l.clearRect(0,
0,c[1].width,c[1].height);var e=a.i,f=a.b;d&&l.drawImage(d,e,f-d.height,c[1].width,d.height);a&&l.drawImage(a,e,f,c[1].width,a.height);g&&l.drawImage(g,e,f+a.height,c[1].width,g.height);f>=c[1].height?(a=m-1,b[1].i=0,b[1].b=f-d.height,0<=a&&t(b,a)):0>f+a.height&&(a=m+1,b[1].i=0,b[1].b=0,a<k&&t(b,a))}function B(d){c[0].style.paddingLeft=(c[1].width-300)/2+"px";var b=Math.floor((Date.now()-d.start)/1E3*d.f)/d.f,a=d.color.substr(1);d.context.save();d.context.clearRect(0,0,300,c[1].height);d.context.translate(150,
c[1].height/2);d.context.rotate(2*Math.PI*b);3==a.length&&(a=a[0]+C[0]+a[1]+a[1]+a[2]+a[2]);for(var b=parseInt(a.substr(0,2),16).toString(),f=parseInt(a.substr(2,2),16).toString(),a=parseInt(a.substr(4,2),16).toString(),e=0;e<d.f;e++)d.context.beginPath(),d.context.rotate(2*Math.PI/d.f),d.context.moveTo(d.g/10,0),d.context.lineTo(d.g/4,0),d.context.lineWidth=d.g/30,d.context.strokeStyle="rgba("+b+","+f+","+a+","+e/d.f+")",d.context.stroke();d.context.restore();y?window.setTimeout(B,d.h,D):d.context.clearRect(0,
0,300,c[1].height)}f=f||{};f={parent:null,offset:0,A:{f:f.f||16,h:f.h||1E3/30,g:f.g||250,back:f.F||"#FFF",color:f.color||"#373737"},j:{dir:f.dir||"assets/",G:!1,C:!1,m:f.m||5,l:f.l||5,B:0,back:f.back||"#FFF"},c:[]};if(void 0===e)return-1;if("string"===typeof e)f.c.push({alt:"",u:"",title:"",url:[e],release:0,v:"",w:!1,s:!1}),e=f;else if(Array.isArray(e)){for(var a=0;a<e.length;a++)if(f.c.push({alt:"",u:"",title:"",url:[],release:0,v:"",w:!1,s:!1}),Array.isArray(e[a]))for(var E=0;E<e[a].length;E++)f.c[a].url.push(e[a][E]);
else f.c[a].url.push(e[a]);e=f}else if(!e.c.length)e.c.push({alt:"",u:"",title:"",url:[],release:0,v:"",w:!1,s:!1});else if(void 0===e.c[0].url)return-1;if(void 0===n||null==n)n=0;var h=e.c,k=e.c.length,y=!0,m=-1,p=e.A,q=e.j,v=[],u=[],z=!1,A=!1,b=[],r={o:1,duration:1},c=[document.createElement("canvas"),document.createElement("canvas")],l=c[1].getContext("2d"),D={context:c[0].getContext("2d"),color:p.color,start:Date.now(),f:p.f,g:p.g,h:p.h},I=[function(){if(0>this.a||this.a>=k||void 0===this.a||
void 0===this.src)return 0;h[this.a].loaded?l.clearRect(0,0,c[1].width,c[1].height):h[this.a].loaded=!0;w(0<=b[0].a?b[0]:0,this,0<=b[2].a?b[2]:0)},function(){if(0>this.a||this.a>=k||void 0===this.a||void 0===this.src)return 0;h[this.a].loaded?l.clearRect(0,0,c[1].width,c[1].height):h[this.a].loaded=!0;w(0<=b[0].a?b[0]:0,this,0<=b[2].a?b[2]:0);y=0},function(){I[0]()}];this.count=function(){return k};this.current=function(){return m};this.go=function(a){a=null===a||void 0===a?0:parseInt(a,10);a=isNaN(a)?
0:a;b[1].i=0;b[1].b=0;t(b,Math.floor(Math.max(0,Math.min(k-1,a))));return a};this.next=function(){var a=m+1;a<k&&(b[1].i=0,b[1].b=0,t(b,a));return a};this.data=function(a){a=null===a||void 0===a?m:parseInt(a,10);return isNaN(a)?h[m]:h[Math.floor(Math.max(0,Math.min(k-1,a)))]};this.scroll=function(a,b){return r={o:a||1,duration:b||1}};this.scrollTo=function(){return-1};c[0].height=480;c[0].style.background=p.back;c[0].style.paddingLeft="170px";c[0].style.zIndex=0;c[0].style.position="absolute";n?n.appendChild(c[0]):
document.body.appendChild(c[0]);window.setTimeout(B,p.h,D);for(a=0;3>a;a++)b.push(new Image),b[a].a=-1,b[a].i=0,b[a].b=0,b[a].addEventListener("load",I[a],!1);for(a=0;a<h.length;a++)h[a].D=a?a==h.length-1?1:0:-1,h[a].loaded=!1;for(a=0;a<e.j.m;a++)u.push(new Image),u[a].a=-1,u[a].addEventListener("load",H,!1);for(a=0;a<e.j.l;a++)v.push(new Image),v[a].a=-1,v[a].addEventListener("load",H,!1);window.onresize=function(){c[1].height=(G/100||.7)*(window.innerHeight||document.documentElement.clientHeight||
document.body.clientHeight);c[1].width=(F/100||.7)*(window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth);w(0<=b[0].a?b[0]:0,b[1],0<=b[2].a?b[2]:0)};c[1].onkeydown=function(a){a=a||window.event;a.preventDefault();if("38"==a.keyCode&&!z){var e=function(){var a=r.o;m>=k-1&&b[1].b-a<0-b[1].height+c[1].height||(b[1].b-=a,l.clearRect(0,0,c[1].width,c[1].height),w(0<=b[0].a?b[0]:0,b[1],0<=b[2].a?b[2]:0));z&&window.setTimeout(e,r.duration)};z=!0;window.setTimeout(e,r.duration)}else if("40"==
a.keyCode&&!A){var f=function(){var a=r.o;0>=m&&0<b[1].b+a||(b[1].b+=a,l.clearRect(0,0,c[1].width,c[1].height),w(0<=b[0].a?b[0]:0,b[1],0<=b[2].a?b[2]:0));A&&window.setTimeout(f,r.duration)};A=!0;window.setTimeout(f,r.duration)}return 0};c[1].onkeyup=function(a){a=a||window.event;"38"==a.keyCode?z=!1:"40"==a.keyCode&&(A=!1)};t(b,void 0===x||null===x||isNaN(x)?q.B:x);c[1].height=(G/100||.7)*(window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight);c[1].width=(F/100||.7)*
(window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth);c[1].background=q.back;c[1].style.zIndex=1;c[1].style.position="relative";c[1].tabIndex=1E3;c[1].style.outline="none";n?n.appendChild(c[1]):document.body.appendChild(c[1])};
