/*
 direction.js (c) 2015 Seun Ogedengbe, MIT*/
direction=function(e,k,v,h){function F(){this.l+=1;if(void 0===window.A&&10>this.l)return window.setTimeout(F,300);jQuery.F.direction=function(a,c,b){return this.D(function(){direction(a,$(this),c,b)})}}function w(a,b){x=!0;window.setTimeout(y,l.g,z);0>b&&(b=0);b>=n&&(b=n-1);g[b].loaded||B.clearRect(0,0,c[1].width,c[1].height);a.a=b;a.src=m.dir+g[b].url[0];r=b;for(var f=0,d=b-1;d>b-m.j-1&&0<=d;d--)g[d].loaded||(t[f].a=d,t[f].src=m.dir+g[d].url,f++);f=0;for(d=b+1;d<m.i+b+1&&d<n;d++)g[d].loaded||(u[f].a=
d,u[f].src=m.dir+g[d].url,f++)}function G(){g[this.a].loaded=!0}function H(a,b){function c(a,b,d){window.scrollBy(Math.floor(a.x)/b,Math.floor(a.y)/b);d+1<5*b&&window.setTimeout(c,5,a,b,d+1)}if(null===a||void 0===a)a={x:0,y:0};else if(isNaN(a)){if(null===a.y||void 0===a.y)a.y=0;if(null===a.x||void 0===a.x)a.x=0}else a={x:0,y:a};if(null===b||void 0===b||0>=b)b=400;0>a.y&&(a.y=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight);0>a.x&&(a.x=window.innerWidth||document.documentElement.clientWidth||
document.body.clientWidth);var d={x:void 0!==window.pageXOffset?a.x-window.pageXOffset:a.x-document.documentElement.scrollLeft,y:void 0!==window.pageYOffset?a.y-window.pageYOffset:a.y-document.documentElement.scrollTop};if(d=={x:0,y:0})return d;window.setTimeout(c,5,d,Math.floor(b/5),0);return d}function y(a){c[0].style.paddingLeft=(c[1].width-300)/2+"px";var b=Math.floor((Date.now()-a.start)/1E3*a.b)/a.b,f=a.color.substr(1);a.context.save();a.context.clearRect(0,0,300,c[1].height);a.context.translate(150,
c[1].height/2);a.context.rotate(2*Math.PI*b);3==f.length&&(f=f[0]+C[0]+f[1]+f[1]+f[2]+f[2]);for(var b=parseInt(f.substr(0,2),16).toString(),d=parseInt(f.substr(2,2),16).toString(),f=parseInt(f.substr(4,2),16).toString(),e=0;e<a.b;e++)a.context.beginPath(),a.context.rotate(2*Math.PI/a.b),a.context.moveTo(a.f/10,0),a.context.lineTo(a.f/4,0),a.context.lineWidth=a.f/30,a.context.strokeStyle="rgba("+b+","+d+","+f+","+e/a.b+")",a.context.stroke();a.context.restore();x?window.setTimeout(y,a.g,z):a.context.clearRect(0,
0,300,c[1].height)}h=h||{};var p={parent:null,offset:0,s:{b:h.b||16,g:h.g||1E3/30,f:h.f||250,back:h.H||"#FFF",color:h.color||"#373737"},h:{dir:h.dir||"assets/",I:!1,B:!1,j:h.j||5,i:h.i||5,w:0,back:h.back||"#FFF"},c:[]};if(void 0===e)return-1;if("string"===typeof e)p.c.push({alt:"",o:"",title:"",url:[e],release:0,u:"",v:!1,m:!1}),e=p;else if(Array.isArray(e)){for(var b=0;b<e.length;b++)if(p.c.push({alt:"",o:"",title:"",url:[],release:0,u:"",v:!1,m:!1}),Array.isArray(e[b]))for(var D=0;D<e[b].length;D++)p.c[b].url.push(e[b][D]);
else p.c[b].url.push(e[b]);e=p}else if(void 0===e.c[0].url)return-1;if(void 0===k||null==k)k=0;var g=e.c,n=e.c.length,x=!0,r=-1,l=e.s,m=e.h,u=[],t=[],q=new Image,E=!0,c=[document.createElement("canvas"),document.createElement("canvas")],B=c[1].getContext("2d"),z={context:c[0].getContext("2d"),color:l.color,start:Date.now(),b:l.b,f:l.f,g:l.g};h.G&&F();this.count=function(){return n};this.current=function(){return r};this.go=function(a){a=null===a||void 0===a?0:parseInt(a,10);a=isNaN(a)?0:a;w(q,Math.floor(Math.max(0,
Math.min(n-1,a))));return a};this.next=function(){var a=r+1;a<n&&w(q,a);return a};this.data=function(a){a=null===a||void 0===a?r:parseInt(a,10);return isNaN(a)?g[r]:g[a]};this.scroll=function(a){return null===a||void 0===a?E:E=a};this.scrollTo=function(a,b){return H(a,b)};c[0].height=480;c[0].style.background=l.back;c[0].style.paddingLeft="170px";c[0].style.zIndex=0;c[0].style.position="absolute";k?k.appendChild(c[0]):document.body.appendChild(c[0]);window.setTimeout(y,l.g,z);q=new Image;q.a=-1;q.addEventListener("load",
function(){g[this.a].loaded?B.clearRect(0,0,this.width,this.height):g[this.a].loaded=!0;c[1].width=this.width;c[1].height=c[0].height=this.height;B.drawImage(this,0,0);x=0;E&&H()},!1);for(b=0;b<g.length;b++)g[b].C=b?b==g.length-1?1:0:-1,g[b].loaded=!1;for(b=0;b<e.h.j;b++)t.push(new Image),t[b].a=-1,t[b].addEventListener("load",G,!1);for(b=0;b<e.h.i;b++)u.push(new Image),u[b].a=-1,u[b].addEventListener("load",G,!1);w(q,void 0===v||null===v||isNaN(v)?m.w:v);c[1].height=480;c[1].width=640;c[1].background=
m.back;c[1].style.zIndex=1;c[1].style.position="relative";k?k.appendChild(c[1]):document.body.appendChild(c[1])};
