/*
 infinite(direction).js (c) 2015 Seun Ogedengbe, MIT*/
infinite=function(e,m,v,f){function w(a,b){window.setTimeout(x,n.g,y);0>b&&(b=0);b>=l&&(b=l-1);h[b].loaded||p.clearRect(0,0,d[1].width,d[1].height);for(var c=0;3>c;c++)a[c].a=b-1+c,b-1+c<l&&0<=b-1+c?a[c].src=q.dir+h[b-1+c].url[0]:(a[c].a=-1,a[c].src="");r=b;for(var c=0,k=b-1;k>b-q.j-1&&0<=k;k--)h[k].loaded||(t[c].a=k,t[c].src=q.dir+h[k].url,c++);c=0;for(k=b+1;k<q.i+b+1&&k<l;k++)h[k].loaded||(u[c].a=k,u[c].src=q.dir+h[k].url,c++)}function B(){h[this.a].loaded=!0}function z(a,b,c){p.clearRect(0,0,d[1].width,
d[1].height);var k=b.x,e=b.y;a&&p.drawImage(a,k-a.height,e,d[1].width,a.height);b&&p.drawImage(b,k,e,d[1].width,b.height);c&&p.drawImage(c,k+b.height,e,d[1].width,c.height)}function x(a){d[0].style.paddingLeft=(d[1].width-300)/2+"px";var b=Math.floor((Date.now()-a.start)/1E3*a.b)/a.b,c=a.color.substr(1);a.context.save();a.context.clearRect(0,0,300,d[1].height);a.context.translate(150,d[1].height/2);a.context.rotate(2*Math.PI*b);3==c.length&&(c=c[0]+C[0]+c[1]+c[1]+c[2]+c[2]);for(var b=parseInt(c.substr(0,
2),16).toString(),e=parseInt(c.substr(2,2),16).toString(),c=parseInt(c.substr(4,2),16).toString(),f=0;f<a.b;f++)a.context.beginPath(),a.context.rotate(2*Math.PI/a.b),a.context.moveTo(a.f/10,0),a.context.lineTo(a.f/4,0),a.context.lineWidth=a.f/30,a.context.strokeStyle="rgba("+b+","+e+","+c+","+f/a.b+")",a.context.stroke();a.context.restore();window.setTimeout(x,a.g,y)}f=f||{};f={parent:null,offset:0,o:{b:f.b||16,g:f.g||1E3/30,f:f.f||250,back:f.B||"#FFF",color:f.color||"#373737"},h:{dir:f.dir||"assets/",
C:!1,w:!1,j:f.j||5,i:f.i||5,v:0,back:f.back||"#FFF"},c:[]};if(void 0===e)return-1;if("string"===typeof e)f.c.push({alt:"",m:"",title:"",url:[e],release:0,s:"",u:!1,l:!1}),e=f;else if(Array.isArray(e)){for(var b=0;b<e.length;b++)if(f.c.push({alt:"",m:"",title:"",url:[],release:0,s:"",u:!1,l:!1}),Array.isArray(e[b]))for(var A=0;A<e[b].length;A++)f.c[b].url.push(e[b][A]);else f.c[b].url.push(e[b]);e=f}else if(void 0===e.c[0].url)return-1;if(void 0===m||null==m)m=0;var h=e.c,l=e.c.length,r=-1,n=e.o,q=
e.h,u=[],t=[],g=[],D=!1,d=[document.createElement("canvas"),document.createElement("canvas")],p=d[1].getContext("2d"),y={context:d[0].getContext("2d"),color:n.color,start:Date.now(),b:n.b,f:n.f,g:n.g},E=[function(){if(0>this.a||this.a>=l||void 0===this.a||void 0===this.src)return 0;h[this.a].loaded?p.clearRect(0,0,d[1].width,d[1].height):h[this.a].loaded=!0;z(0<=g[0].a?g[0]:0,this,0<=g[2].a?g[2]:0)},function(){if(0>this.a||this.a>=l||void 0===this.a||void 0===this.src)return 0;h[this.a].loaded?p.clearRect(0,
0,d[1].width,d[1].height):h[this.a].loaded=!0;z(0<=g[0].a?g[0]:0,this,0<=g[2].a?g[2]:0)},function(){E[0]()}];this.count=function(){return l};this.current=function(){return r};this.go=function(a){a=null===a||void 0===a?0:parseInt(a,10);a=isNaN(a)?0:a;w(master,Math.floor(Math.max(0,Math.min(l-1,a))));return a};this.next=function(){var a=r+1;a<l&&w(master,a);return a};this.data=function(a){a=null===a||void 0===a?r:parseInt(a,10);return isNaN(a)?h[r]:h[a]};this.scroll=function(a){return null===a||void 0===
a?D:D=a};this.scrollTo=function(a){return{x:void 0!==window.pageXOffset?a.x-window.pageXOffset:a.x-document.documentElement.scrollLeft,y:void 0!==window.pageYOffset?a.y-window.pageYOffset:a.y-document.documentElement.scrollTop}};d[0].height=480;d[0].style.background=n.back;d[0].style.paddingLeft="170px";d[0].style.zIndex=0;d[0].style.position="absolute";m?m.appendChild(d[0]):document.body.appendChild(d[0]);window.setTimeout(x,n.g,y);for(b=0;3>b;b++)g.push(new Image),g[b].a=-1,g[b].x=0,g[b].y=0,g[b].addEventListener("load",
E[b],!1);for(b=0;b<h.length;b++)h[b].A=b?b==h.length-1?1:0:-1,h[b].loaded=!1;for(b=0;b<e.h.j;b++)t.push(new Image),t[b].a=-1,t[b].addEventListener("load",B,!1);for(b=0;b<e.h.i;b++)u.push(new Image),u[b].a=-1,u[b].addEventListener("load",B,!1);window.onresize=function(){d[1].height=.7*(window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight);d[1].width=.7*(window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth);z(0<=g[0].a?g[0]:0,this,0<=g[2].a?
g[2]:0)};w(g,void 0===v||null===v||isNaN(v)?q.v:v);d[1].height=.7*(window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight);d[1].width=.7*(window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth);d[1].background=q.back;d[1].style.zIndex=1;d[1].style.position="relative";m?m.appendChild(d[1]):document.body.appendChild(d[1])};
